// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyqfrrgbnmamzbncervw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5cWZycmdibm1hbXpibmNlcnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDEyODIsImV4cCI6MjA2NTk3NzI4Mn0.41xBXpms99MvaN5zvO5YqVapQJompqYjCzIzdG2_0_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);